# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Directory structure
source: src/
destination: dist/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ellipsis · Get work done in chat
email: info@ellipsis.ai
description: > # this means to ignore newlines until "baseurl:"
  Ellipsis is a bot that helps you build and run sophisticated workflows in chat — where your team already works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ellipsis.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: EllipsisBot
github_username:  ellipsis-ai
google_analytics: UA-86412831-1
header_pages:
  - about.html
  - contact.html

## Enable a different asset URL to test changes to the assets
## S3 direct (skip cloudfront cache):
# assetUrl: http://ellipsis-assets.s3-website-us-east-1.amazonaws.com
assetUrl: https://assets.ellipsis.ai

# This refers to the desired asset tag as deployed by the production app to S3
assetTag: 3b436c4365d59a6ee162337637d4bf8b

# Build settings
markdown: kramdown
# gems:
exclude:
  - Gemfile
  - Gemfile.lock

#collections:
#  faqs:
#    output: true
